### ISSUE TITLE
Не получается запустить чат.

### ISSUE THREAD

**Issue by coaperator** [iliakan/nodejs-screencast#6]
Здравствуйте Илья!
Огромное спасибо за скринкаст. Пробую изучать nodejs, не все пока получается.
Пробовал запустить ваш чат локально. но так и не удалось, неделю мучаюсь почти.
Проблема в том что все время какие то ошибки вываливаются. с горем пополам подобрал те компоненты которые должны быть в node_modules(package.json в архиве не было), чтобы не было ошибок, в итоге сайт запустился, чат нет.
На данный момент версия socket.io последняя 1.4.8
С ней естественно не работает.
На оф. сайте демо пример чата тоже не работает. чтобы посомотреть..

Вопрос в следующем, не могли бы вы подсказать, что нужно поменять, какие важные изменения в коде сделать, чтобы запустился чат на версии socket.io 1.4.8

Из того что я сам выяснил:
- при установке не создается папка socket.io-client в папке public\vendor\bower_components
- не работает ваш логер(я на винде, слеши в коде прямые стоят) - его я отключил, чтобы убрать ошибку.
- в клиентской части чата не срабатывают .on('leave', и .on('join', из за этого не активируется поле для отправки. и .on('message', тоже. естественно не отправляются сообшения
- в серверной версии похоже не принимается ничего..

согласно этой инструкции http://stackoverflow.com/questions/34370507/socket-connection-closed-before-receiving-a-handshake-response
надо подключать https://cdn.socket.io/socket.io-1.3.7.js, но что то все равно не работает.
выдает ошибку доступа.

С ув. Алекс. очень жду ответа.

**Comment by iliakan** [comment]
Со старым сокетом оно работало. Честно говоря, это серия - как раз самая устаревшая из скринкаста.

**Comment by coaperator** [comment]
да я вижу. но стоящих видеоуроков кроме вашего не знаю. в вашем уроке я хоть понимаю что делаю хотя бы примерно.
я из всего урока не смог переписать на новые версии пакетов только сокеты.

**Comment by aportx** [comment]
Здравствуйте Илья!
Прошу вашей помощи. замучился уже и чего я только не попрробовал.
проблема следующая:
при запуске сервера устанавливается соединение - тут вроде наладил его работу с горем пополам.
в логах:
  socket.io:server initializing namespace / +0ms
  socket.io:server creating engine.io instance with opts {"path":"/socket.io"} +2ms
  socket.io:server attaching client serving req handler +3ms
Express server listening on port 80
  socket.io:server incoming connection with id 16t4AWaDr0cnmTPbAAAA +1s
  socket.io:client connecting to namespace / +1ms
  socket.io:namespace adding socket to nsp / +0ms

но вот поле с инпутом не активируется все равно. как я понимаю после установления соединения не срабатывает этот кусочек кода:
.on('connect', function() {
        printStatus("соединение установлено");
        form.on('submit', sendMessage);
        input.prop('disabled', false);
      })

Ошибок никаких при любых действиях не выдает.
Подскажите пожалуйста, в чем может быть проблема?
socket.io установил последнюю версию 1.4.5
